{ -*- buffer-read-only: t -*- }

{ Unit automatically generated by image2pascal tool,
  to embed images in Pascal source code.
  @exclude (Exclude this unit from PasDoc documentation.) }
unit GVIImages;

interface

uses CastleImages;

var
  Invalid: TRGBImage;

var
  Welcome: TRGBAlphaImage;

implementation

uses SysUtils;

{ Actual image data is included from another file, with a deliberately
  non-Pascal file extension ".image_data". This way online code analysis
  tools will NOT consider this source code as an uncommented Pascal code
  (which would be unfair --- the image data file is autogenerated
  and never supposed to be processed by a human). }
{$I gviimages.image_data}

initialization
  Invalid := TRGBImage.Create(InvalidWidth, InvalidHeight, InvalidDepth);
  Move(InvalidPixels, Invalid.RawPixels^, SizeOf(InvalidPixels));
  Invalid.URL := 'embedded-image:/Invalid';
  Welcome := TRGBAlphaImage.Create(WelcomeWidth, WelcomeHeight, WelcomeDepth);
  Move(WelcomePixels, Welcome.RawPixels^, SizeOf(WelcomePixels));
  Welcome.URL := 'embedded-image:/Welcome';
finalization
  FreeAndNil(Invalid);
  FreeAndNil(Welcome);
end.